import type { VolunteerAssignment } from "./schemas";

export const INITIAL_ASSIGNMENTS: VolunteerAssignment[] = [
  {
    id: "prasad-serving",
    title: "Prasad Serving",
    time: "10:30 AM – 12:30 PM",
    location: "Dining Area",
    description: "Help serve prasad and guide guests through the serving line.",
    skillLevel: "Easy",
    totalSpots: 4,
    filledSpots: 2,
  },
  {
    id: "parking-guidance",
    title: "Parking Guidance",
    time: "8:30 AM – 10:30 AM",
    location: "Parking Lot",
    description: "Help direct cars and guide guests to available parking.",
    skillLevel: "Medium",
    totalSpots: 3,
    filledSpots: 2,
  },
  {
    id: "setup-team",
    title: "Setup Team",
    time: "8:00 AM – 9:30 AM",
    location: "Main Hall",
    description: "Help arrange chairs, tables, signs, and event materials.",
    skillLevel: "Easy",
    totalSpots: 5,
    filledSpots: 2,
  },
  {
    id: "guest-checkin",
    title: "Guest Check-In",
    time: "9:00 AM – 11:00 AM",
    location: "Entrance",
    description: "Welcome guests and help with basic event check-in.",
    skillLevel: "Easy",
    totalSpots: 2,
    filledSpots: 1,
  },
  {
    id: "cleanup-team",
    title: "Cleanup Team",
    time: "12:30 PM – 1:30 PM",
    location: "Main Hall",
    description: "Help clean and reset the hall after the event.",
    skillLevel: "Easy",
    totalSpots: 4,
    filledSpots: 0,
  },
  {
    id: "tech-help-desk",
    title: "Tech Help Desk",
    time: "9:30 AM – 11:30 AM",
    location: "Lobby",
    description: "Help guests scan QR codes, submit forms, or access event links.",
    skillLevel: "Experienced",
    totalSpots: 2,
    filledSpots: 1,
  },
];
